### ISSUE TITLE
Access blocked: This app’s request is invalid (sign in problem)

### ISSUE THREAD

**Issue by BhanuKr** [vanshdhar999/College-ecommerce#7]
Access blocked: This app’s request is invalid (sign in problem)
![Screenshot 2024-01-23 005732](https://github.com/vanshdhar999/College-ecommerce/assets/115964594/1d9494be-0367-45a3-998b-49ef43782f11)

**Comment by vanshdhar999** [comment]
Fixed 
Added the url's in the OAuth client
